services:
  - type: web
    name: solana-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false

  - type: worker
    name: solana-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python vertix-trader.py
    plan: free
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
